# <font color = red> Cosine Similarity </font>

In [171]:
#https://www.brilliantcode.net/1062/numpy-tutorial-basic-operations/

## <mark style=background-color:yellow>1. import 所需套件 </mark> 

In [172]:
import pandas as pd
import numpy as np

In [173]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics.pairwise import pairwise_distances

In [174]:
from scipy.spatial.distance import pdist

## <mark style=background-color:grey>視覺化 所需套件 </mark> 

In [175]:
import matplotlib.pyplot as plt

## <mark style=background-color:grey>formatting 所需套件 </mark> 

In [176]:
import locale
locale.setlocale(locale.LC_ALL, '') 

'Chinese (Traditional)_Taiwan.950'

## <mark style=background-color:yellow> function </mark> 

## <mark style=background-color:grey>  歐式距離euclidean distance </mark> 

In [178]:
def func_euclidean_distance(data1, data2):
    points = zip(data1, data2)
    print(type(points), points)
    diffs_squared_distance = [pow(a - b, 2) for (a, b) in points]
    return math.sqrt(sum(diffs_squared_distance))

# <mark style=background-color:yellow>  cosine similarity </mark> 

In [179]:
#$$P(A \mid B) = \frac{ P(B \mid A) P(A) }{ P(B) }$$
#https://www.cnblogs.com/laoduan/p/7641698.html
#餘弦 -1 ~ 1越相似

$$ Cosine  Similarity餘弦相似度 =  \frac{ A矩陣    X    B矩陣  }{ |A| |B| } $$

In [180]:

#方法1: 使用 loop 慢慢累積兩個矩陣的乘積 
def func_cosine_similarity(vector1, vector2):
    dot_product = 0.0
    normA = 0.0
    normB = 0.0
    for a, b in zip(vector1, vector2):
        print('a=',a , end=' ; ')
        print('b=',b, end=' ; ')
        dot_product += a * b
        print('accumulated dot_product=', dot_product)
        
        normA += a ** 2
        print('+', a ** 2,' ; ', 'accumulated normA=',  normA)
        normB += b ** 2
        print('+', b ** 2,' ; ', 'accumulated normB=',   normB, '\n')
        
    if normA == 0.0 or normB == 0.0:
        return None
    else:
        print('accumulated dot_product 分子=', dot_product )
        print('accumulated normA 分母1=',(normA ), end=' ; ' )
        print('accumulated normB 分母2=',(normB ) )
        # ** 0.5 就是開根號
        print('分母相乘後, 開完根號=', ((normA * normB) ** 0.5))
        print('    註: 分母1*分母2=',(normA * normB) )  
        print('分子/分母相乘後開完根號=', dot_product / ((normA * normB) ** 0.5))
        return dot_product / ((normA * normB) ** 0.5)

In [181]:
# 方法1: call function func_cosine_similarity
print('\n cosine similarity=', f'{ (func_cosine_similarity([1,3,2],[2,2,1])) :.2f}')

a= 1 ; b= 2 ; accumulated dot_product= 2.0
+ 1  ;  accumulated normA= 1.0
+ 4  ;  accumulated normB= 4.0 

a= 3 ; b= 2 ; accumulated dot_product= 8.0
+ 9  ;  accumulated normA= 10.0
+ 4  ;  accumulated normB= 8.0 

a= 2 ; b= 1 ; accumulated dot_product= 10.0
+ 4  ;  accumulated normA= 14.0
+ 1  ;  accumulated normB= 9.0 

accumulated dot_product 分子= 10.0
accumulated normA 分母1= 14.0 ; accumulated normB 分母2= 9.0
分母相乘後, 開完根號= 11.224972160321824
    註: 分母1*分母2= 126.0
分子/分母相乘後開完根號= 0.8908708063747479

 cosine similarity= 0.89


In [182]:
#方法2: 使用 numpy matrix 計算兩個矩陣的乘積 a* b就好了
def func_cos_sim(vector_a, vector_b):
    """
    計算兩個向量之間的餘弦相似度
    :param vector_a: 向量 a 
    :param vector_b: 向量 b 
    """
    vector_a = np.mat(vector_a) #2D matrix
    print('vector_a=', vector_a, 'type=', type(vector_a) )
    vector_b = np.mat(vector_b) #2D matrix
    print('vector_b=', vector_b, 'type=', type(vector_b) )
    
    print('vector_b.T=', vector_b.T,'\n')
    num = float(vector_a * vector_b.T) #分子
    print('float(vector_a * vector_b.T)=',num)
    
    print('np.linalg.norm(vector_a) 分母1開完根號後=', np.linalg.norm(vector_a)) 
    print('np.linalg.norm(vector_b) 分母2開完根號後=', np.linalg.norm(vector_b))    
    denom = np.linalg.norm(vector_a) * np.linalg.norm(vector_b)  #分母
    print( '開完根號的分母1 * 開完根號的分母2 =', denom)
    sim = num / denom
    print('分子/ 分母=', f'{sim:.2f}')
     
    return sim

In [183]:
#方法2: call func_cos_sim 使用 numpy matrix 計算兩個矩陣的乘積 a* b就好了
A= [1,3,2]
B= [2,2,1]
print('\n cosine similarity=', f'{ (func_cos_sim(A,B)) :.2f}')

vector_a= [[1 3 2]] type= <class 'numpy.matrix'>
vector_b= [[2 2 1]] type= <class 'numpy.matrix'>
vector_b.T= [[2]
 [2]
 [1]] 

float(vector_a * vector_b.T)= 10.0
np.linalg.norm(vector_a) 分母1開完根號後= 3.7416573867739413
np.linalg.norm(vector_b) 分母2開完根號後= 3.0
開完根號的分母1 * 開完根號的分母2 = 11.224972160321824
分子/ 分母= 0.89

 cosine similarity= 0.89


In [184]:
# 方法3: 直接寫公式
A= [1,3,2]
B= [2,2,1]
print('分子 AB矩陣乘積=',np.dot(A,B), '\n')
print('分母A平方累計值&開完根號=', np.linalg.norm([1,3,2]))
print('分母B平方累計值&開完根號=', np.linalg.norm([2,2,1]))

d1=np.dot(A,B)/(np.linalg.norm(A)*np.linalg.norm(B))
print('分母AB 都開完根號 相乘=', (np.linalg.norm(A)*np.linalg.norm(B)))
print('\n 分子 / (AB兩個分母都開完根號 相乘)=', f'{d1:.2f}')

分子 AB矩陣乘積= 10 

分母A平方累計值&開完根號= 3.7416573867739413
分母B平方累計值&開完根號= 3.0
分母AB 都開完根號 相乘= 11.224972160321824

 分子 / (AB兩個分母都開完根號 相乘)= 0.89


In [185]:
# 方法4:直接寫 one line 公式  
# 使用 power, sqrt
def func_cos_sim_oneline(v1, v2):
    print('分子 AB矩陣乘積=', np.dot(v1, v2))
    print('分母A平方累計值&開完根號=', (np.sqrt(np.sum(np.power(v1, 2)))))
    print('分母B平方累計值&開完根號=',np.sqrt(np.sum(np.power(v2, 2))))
    print('最終分母=',(np.sqrt(np.sum(np.power(v1, 2))) * np.sqrt(np.sum(np.power(v2, 2)))))
    return np.dot(v1, v2) / (np.sqrt(np.sum(np.power(v1, 2))) * np.sqrt(np.sum(np.power(v2, 2))))

In [186]:
# 方法4: call 直接寫公式 func_cos_sim_oneline
A= [1,3,2]
B= [2,2,1]
print('\n cosine similarity=', f'{ (func_cos_sim_oneline(A,B)) :.2f}')

分子 AB矩陣乘積= 10
分母A平方累計值&開完根號= 3.7416573867739413
分母B平方累計值&開完根號= 3.0
最終分母= 11.224972160321824

 cosine similarity= 0.89


In [187]:
# 方法5: 使用scipy 先計算consine 距離 pdist 
#from scipy.spatial.distance import pdist
X=np.vstack([[1,3,2],[2,2,1]])
print('type of np.vstack=', type(X),'\n')
print('np.vstack=',X)
print("pdist(np.vstack,'cosine')=", pdist(X,'cosine'))

d2=1-pdist(X,'cosine')
#不能直接寫 f'{d2:.2f}'
print('cosine similarity=', f'{ d2[0] :.2f}')

type of np.vstack= <class 'numpy.ndarray'> 

np.vstack= [[1 3 2]
 [2 2 1]]
pdist(np.vstack,'cosine')= [0.10912919]
cosine similarity= 0.89


# <mark style=background-color:yellow>Calculate Vectors </mark> 

In [188]:
def func_build_word_vector(text):
    word2id = {w: i for i, w in enumerate(sorted(list(set(func_reduce(lambda a, b: a + b, text)))))}
    id2word = {x[1]: x[0] for x in word2id.items()}
    wvectors = np.zeros((len(word2id), len(word2id)))
    for sentence in text:
        for word1, word2 in zip(sentence[:-1], sentence[1:]):
            id1, id2 = word2id[word1], word2id[word2]
            wvectors[id1, id2] += 1
            wvectors[id2, id1] += 1
    return wvectors, word2id, id2word

In [190]:
#frac{分子}{分母}

#x 平方  $$x^2$$ 

## <mark style=background-color:grey> 矩陣相乘 </mark> 

In [191]:
a=np.mat('4 3; 2 1') #a是矩陣
b=np.mat('1 2; 3 4') #b是矩陣
print(a)
# [[4 3]
#  [2 1]]
print(b)
# [[1 2]
#  [3 4]]
print(a*b)  #a*b是matrix 矩陣
print(type(a*b))
# [[13 20]
#  [ 5  8]]

[[4 3]
 [2 1]]
[[1 2]
 [3 4]]
[[13 20]
 [ 5  8]]
<class 'numpy.matrix'>


In [192]:
c=np.array([[4, 3], [2, 1]]) #c是 2darrary
d=np.array([[1, 2], [3, 4]]) #d是 2darrary
print(c*d)                   #c*d是 2darrary
print(type(c*d))
# [[4 6]
#  [6 4]]

[[4 6]
 [6 4]]
<class 'numpy.ndarray'>


In [193]:
print(np.dot(c,d))
# [[13 20]
#  [ 5  8]]

[[13 20]
 [ 5  8]]


In [194]:
# 矩陣相乘 如果原始資料是array ,要使用 A.dot(B)
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("A, B相乘(array 的矩陣乘法A.dob(B) =>\n {0}".format(  A.dot(B)  )      )
print()
# 1 [5 6] + 2[7 8]
# 3 [5 6] + 4 [7 8]

# [5 6 ] + [14 16]
# [15 18] + [28 32]

# [19 22] [43 50]

print("A, B相對應位置相乘=>\n {0}".format(A*B))

A, B相乘(array 的矩陣乘法A.dob(B) =>
 [[19 22]
 [43 50]]

A, B相對應位置相乘=>
 [[ 5 12]
 [21 32]]


In [195]:
# 矩陣相乘 如果原始資料是 matrix ,要使用 A*B
A=np.mat('1 2; 3 4') #a是矩陣
B=np.mat('5 6; 7 8') #b是矩陣
A*B

matrix([[19, 22],
        [43, 50]])

## <mark style=background-color:grey> 餘弦相似度 </mark> 

In [196]:
a=[[1,3,2],[2,2,1]]
#from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(a) #使用package

array([[1.        , 0.89087081],
       [0.89087081, 1.        ]])

## <mark style=background-color:grey> 餘弦距離 = 1 - 餘弦相似度;距離小則相似度高 </mark> 

In [197]:
#傳入一個變數a時，返回陣列的第i row 第j column 表示a[i]與a[j]的餘弦距離
a=[[1,3,2],[2,2,1]]
pairwise_distances(a,metric="cosine")  #使用package

array([[0.        , 0.10912919],
       [0.10912919, 0.        ]])